CREATE TABLE IF NOT EXISTS ACTIVITY (
ID_ACTIVITY varchar(36) NOT NULL UNIQUE,
NAME VARCHAR(255),
MAX_DATE TIMESTAMP ,
CONSTRAINT PK_ACTIVITY PRIMARY KEY
(ID_ACTIVITY)
);

CREATE TABLE IF NOT EXISTS ACTIVITY_USER(
ID_ACTIVITY varchar(36) NOT NULL,
ID_USER int(10) NOT NULL,
MARK int(10),
FINISHED BOOLEAN,
CONSTRAINT PK_ACTIVITY_USER PRIMARY KEY
(ID_ACTIVITY, ID_USER)
);


CREATE TABLE IF NOT EXISTS ACTIVITY_GROUP(
ID_GROUP int(10) NOT NULL,
ID_ACTIVITY varchar(36) NOT NULL,
CONSTRAINT PK_ACTIVITY_GROUP PRIMARY KEY
(ID_GROUP, ID_ACTIVITY)
);